### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by oneEyedSunday** [maxcohn/mlisp#1]
Hello there, I'm in grad school and I'm thinking of trying my hands on language design. 
Found this repo on /r/programming.
That aside I was wondering if you could make a contributing guide for people who want to contribute to this project. And also a kinder introduction. I have no idea how to actually test this out for instance.

**Comment by maxcohn** [comment]
Yeah, that would be great! What do you need from me to get started?

**Comment by oneEyedSunday** [comment]
Firstly i wanna get a feel of this, so I would like to know:
   * How to actually run the `interpreter`/`parser`
as I do not see a `main.py` or `index.py`

**Comment by maxcohn** [comment]
`repl.py` opens up a Read-Evaluate-Print loop for running code expression by expression. `run.py` takes a file as input and then runs the entire file. So if I wanted to run `knapsack.py` you would use the command: `python3 run.py examples/knapsack.lisp`. 

I'll make a better explanation of each file in the README after I get out of work for the day.

**Comment by oneEyedSunday** [comment]
Ok, that'd be nice. Thanks
